# Generated by Django 6.0 on 2025-12-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('SALONGO', 'Salongo Populaire'), ('FORMATION', 'Formation & Sensibilisation'), ('CAMPAGNE', 'Campagne de Salubrité')], default='SALONGO', max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(help_text='Commune ou Quartier (ex: Kinshasa)', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('phone', models.CharField(help_text='Essentiel pour la coordination terrain', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('PARTICIPANT', 'Participant Salongo'), ('LEADER', 'Chef de Quartier / Leader'), ('ECO_BRIGADE', 'Membre Eco-Brigade')], default='PARTICIPANT', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('PRESENT', 'Présent sur le terrain')], default='PENDING', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='events.event', verbose_name='Événement ciblé')),
            ],
            options={
                'verbose_name': 'Bénévole / Participant',
                'verbose_name_plural': 'Gestion des Bénévoles',
            },
        ),
    ]
