# Generated by Django 6.0 on 2025-12-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Ex: -4.325 (Kinshasa)', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Ex: 15.322', null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='event',
            name='map_status',
            field=models.CharField(choices=[('PLANNED', 'Planifié (Bleu)'), ('COMPLETED', 'Réalisé (Vert)')], default='PLANNED', max_length=20, verbose_name='Statut Carte'),
        ),
    ]
