# Generated by Django 5.2.9 on 2025-12-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_id_alter_eventimage_id_and_more'),
        ('events', '0004_event_description_en_event_description_fr_and_more'),
    ]

    operations = [
    ]
