# Generated by Django 6.0 on 2025-12-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre principal')),
                ('subtitle', models.TextField(verbose_name='Sous-titre / Description')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Image de fond')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Texte du bouton')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='Lien (ex: /donate)')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Slide d'accueil",
                'verbose_name_plural': 'Carousel Accueil',
                'ordering': ['order'],
            },
        ),
    ]
