# Generated by Django 6.0 on 2025-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='Sous-titre / Description'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='subtitle_fr',
            field=models.TextField(null=True, verbose_name='Sous-titre / Description'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre principal'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre principal'),
        ),
    ]
