# Generated by Django 5.2.9 on 2025-12-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carouselitem_id'),
        ('core', '0002_carouselitem_button_text_en_and_more'),
    ]

    operations = [
    ]
