# Generated by Django 6.0 on 2025-12-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre / Lieu')),
                ('image', models.ImageField(upload_to='gallery/showcase/')),
                ('category', models.CharField(choices=[('SALONGO', 'Activités & Salongo'), ('SEMINAR', 'Séminaires & Conférences'), ('IMPACT', 'Impact (Avant/Après)'), ('TEAM', "Vie d'équipe")], default='SALONGO', max_length=20)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Légende (Optionnel)')),
                ('date_taken', models.DateField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image Galerie',
                'verbose_name_plural': 'Galerie Multimédia',
                'ordering': ['-date_taken', '-created_at'],
            },
        ),
    ]
