# Generated by Django 6.0 on 2025-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('role', models.CharField(help_text='Ex: Coordonnateur Principal', max_length=100, verbose_name='Titre du poste')),
                ('category', models.CharField(choices=[('COORD', 'Coordination Générale'), ('TERRAIN', 'Opérations & Terrain'), ('COM', 'Communication & Partenariats'), ('TECH', 'Support Technique & Logistique')], default='TERRAIN', max_length=20, verbose_name='Département')),
                ('bio', models.TextField(blank=True, verbose_name='Courte biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Lien LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Lien Twitter/X')),
                ('order', models.IntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': 'Équipe PNAC',
                'ordering': ['order', 'name'],
            },
        ),
    ]
