# Generated by Django 6.0 on 2025-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Courte biographie'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Courte biographie'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='category_en',
            field=models.CharField(choices=[('COORD', 'Coordination Générale'), ('TERRAIN', 'Opérations & Terrain'), ('COM', 'Communication & Partenariats'), ('TECH', 'Support Technique & Logistique')], default='TERRAIN', max_length=20, null=True, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='category_fr',
            field=models.CharField(choices=[('COORD', 'Coordination Générale'), ('TERRAIN', 'Opérations & Terrain'), ('COM', 'Communication & Partenariats'), ('TECH', 'Support Technique & Logistique')], default='TERRAIN', max_length=20, null=True, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(help_text='Ex: Coordonnateur Principal', max_length=100, null=True, verbose_name='Titre du poste'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_fr',
            field=models.CharField(help_text='Ex: Coordonnateur Principal', max_length=100, null=True, verbose_name='Titre du poste'),
        ),
    ]
