# Generated by Django 5.2.9 on 2025-12-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_id'),
        ('team', '0002_teammember_bio_en_teammember_bio_fr_and_more'),
    ]

    operations = [
    ]
