"""
Django settings for pnac_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

from dotenv import load_dotenv

load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xlse3^i8mwcoy*tm!ol-k3b7v97&ad(0&x%)d5=c9mm2d%ep*_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['pnac-rdc.org', 'www.pnac-rdc.org', 'localhost', '127.0.0.1']
SECURE_SSL_REDIRECT = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'core',
    'donations',
    'events',
    'team',
    'seminars',
    'resources',
    'gallery',
    'blog',
    'forum',
]

JAZZMIN_SETTINGS = {
    "site_title": "CMS PNAC",
    "site_header": "PNAC RDC",
    "site_brand": "CMS PNAC",
    "site_logo": "images/Logo.png",
    "login_logo": "images/Logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "images/favicon-32x32.png",
    "welcome_sign": "Espace de publication et de gestion du PNAC",
    "copyright": "PNAC RDC — Unis pour assainir",
    "search_model": ["blog.Post", "events.Event", "team.TeamMember"],
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "related_modal_active": True,
    "language_chooser": True,
    "use_google_fonts_cdn": True,
    "changeform_format": "collapsible",
    "changeform_format_overrides": {
        "auth.user": "horizontal_tabs",
        "auth.group": "vertical_tabs",
    },
    "topmenu_links": [
        {"name": "Voir le site", "url": "home", "new_window": True},
        {"name": "Nouvel article", "url": "admin:blog_post_add", "icon": "fas fa-plus"},
        {"name": "Nouvelle action", "url": "admin:events_event_add"},
        {"model": "blog.Post"},
    ],
    "usermenu_links": [
        {"name": "Site public", "url": "home", "new_window": True},
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "blog.Post": "fas fa-newspaper",
        "core.CarouselItem": "fas fa-images",
        "events.Event": "fas fa-broom",
        "events.Volunteer": "fas fa-hand-paper",
        "events.EventImage": "fas fa-camera",
        "gallery.GalleryImage": "fas fa-photo-video",
        "resources.Resource": "fas fa-file-alt",
        "team.TeamMember": "fas fa-id-badge",
        "team.VolunteerApplication": "fas fa-user-plus",
        "team.PhoneOTP": "fas fa-sms",
        "forum.Topic": "fas fa-comments",
        "forum.Post": "fas fa-comment-dots",
        "forum.TopicAccessRequest": "fas fa-user-lock",
        "seminars.Seminar": "fas fa-chalkboard-teacher",
        "seminars.SeminarRegistration": "fas fa-clipboard-list",
    },
    "order_with_respect_to": [
        "blog",
        "core",
        "events",
        "gallery",
        "resources",
        "seminars",
        "team",
        "forum",
        "auth",
    ],
    "hide_models": ["team.PhoneOTP"],
    "custom_css": "admin/css/pnac_cms.css",
    "custom_js": "admin/js/pnac_cms.js",
    "custom_links": {
        "blog": [
            {
                "name": "Articles publiés",
                "url": "post_list",
                "icon": "fas fa-eye",
                "permissions": ["blog.view_post"],
            }
        ],
        "events": [
            {
                "name": "Actions sur le site",
                "url": "event_list",
                "icon": "fas fa-external-link-alt",
                "permissions": ["events.view_event"],
            }
        ],
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pnac_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            './templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'team.context_processors.member_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'pnac_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv("DBENGINE"),
        'NAME': os.getenv("DBNAME"),
        'USER': os.getenv("DBUSER"),
        'PASSWORD': os.getenv("DBPASSWORD"),
        'HOST': os.getenv("DBHOST", "localhost"), # Use 'localhost' for local development
        'PORT': os.getenv("DBPORT", "3306"),          # Leave blank to use default port 
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'team.backends.MemberAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = 'member_login'
LOGIN_REDIRECT_URL = 'member_dashboard'
LOGOUT_REDIRECT_URL = 'member_login'

INFOBIP_BASE_URL = os.getenv('INFOBIP_BASE_URL', '')
INFOBIP_API_KEY = os.getenv('INFOBIP_API_KEY', '')
INFOBIP_SENDER = os.getenv('INFOBIP_SENDER', 'PNAC')


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', _('Français')),
    ('en', _('English')),
]

USE_I18N = True
USE_L10N = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = "/home/mote8725/public_html/static"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

X_FRAME_OPTIONS = "SAMEORIGIN"

# settings.py

MAXICASH_MERCHANT_ID = os.getenv("MAXICASH_MERCHANT_ID") # Fourni par MaxiCash
MAXICASH_MERCHANT_PASSWORD = os.getenv("MAXICASH_MERCHANT_ID") # Fourni par MaxiCash
MAXICASH_ENV = "sandbox" # ou "live" pour la production
MAXICASH_GATEWAY_URL = "https://api-test.maxicashapp.com/PayEntryPost" # URL de test
# Pour la prod : "https://api.maxicashapp.com/PayEntryPost"

CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"
CKEDITOR_5_MAX_FILE_SIZE = 5
CKEDITOR_5_USER_LANGUAGE = True
CKEDITOR_5_CUSTOM_CSS = "admin/css/ckeditor_content.css"
CKEDITOR_5_CONFIGS = {
    "default": {
        "language": "fr",
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "link",
            "|",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "|",
            "undo",
            "redo",
        ],
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Paragraphe", "class": "ck-heading_paragraph"},
                {"model": "heading2", "view": "h2", "title": "Titre", "class": "ck-heading_heading2"},
                {"model": "heading3", "view": "h3", "title": "Sous-titre", "class": "ck-heading_heading3"},
            ]
        },
    },
    "cms": {
        "language": "fr",
        "toolbar": {
            "items": [
                "heading",
                "|",
                "bold",
                "italic",
                "underline",
                "link",
                "|",
                "bulletedList",
                "numberedList",
                "outdent",
                "indent",
                "alignment",
                "|",
                "blockQuote",
                "insertTable",
                "insertImage",
                "mediaEmbed",
                "horizontalLine",
                "|",
                "undo",
                "redo",
                "sourceEditing",
                "removeFormat",
            ],
            "shouldNotGroupWhenFull": True,
        },
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignCenter",
                "imageStyle:alignRight",
            ],
        },
        "table": {
            "contentToolbar": ["tableColumn", "tableRow", "mergeTableCells"],
        },
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Paragraphe", "class": "ck-heading_paragraph"},
                {"model": "heading2", "view": "h2", "title": "Titre de section", "class": "ck-heading_heading2"},
                {"model": "heading3", "view": "h3", "title": "Sous-titre", "class": "ck-heading_heading3"},
            ]
        },
    },
}