# Generated by Django 6.0 on 2025-12-17 06:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la conférence')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='seminars/')),
                ('start_date', models.DateTimeField(verbose_name='Début')),
                ('end_date', models.DateTimeField(verbose_name='Fin')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu (Hôtel/Salle)')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Frais d'inscription ($)")),
                ('accommodation_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Laisser à 0 si non proposé', max_digits=10, verbose_name='Frais Hébergement / Nuit ($)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Organisation / Entreprise')),
                ('phone', models.CharField(max_length=20)),
                ('participant_type', models.CharField(choices=[('PARTICIPANT', 'Participant Individuel'), ('PARTNER', 'Partenaire / Sponsor'), ('SPEAKER', 'Intervenant')], default='PARTICIPANT', max_length=20)),
                ('origin', models.CharField(choices=[('LOCAL', 'National (RDC)'), ('INTL', 'International (Étranger)')], default='LOCAL', max_length=10)),
                ('needs_accommodation', models.BooleanField(default=False, verbose_name="Besoin d'hébergement")),
                ('accommodation_nights', models.PositiveIntegerField(default=0, verbose_name='Nombre de nuits')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('CONFIRMED', 'Confirmé & Payé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='seminars.seminar')),
            ],
        ),
    ]
