# Generated by Django 6.0 on 2025-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='end_date_en',
            field=models.DateTimeField(null=True, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='end_date_fr',
            field=models.DateTimeField(null=True, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='start_date_en',
            field=models.DateTimeField(null=True, verbose_name='Début'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='start_date_fr',
            field=models.DateTimeField(null=True, verbose_name='Début'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre de la conférence'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre de la conférence'),
        ),
    ]
