# Generated by Django 5.2.9 on 2025-12-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_alter_seminar_id_alter_seminarregistration_id'),
        ('seminars', '0002_seminar_description_en_seminar_description_fr_and_more'),
    ]

    operations = [
    ]
