# Generated by Django 6.0 on 2025-12-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, verbose_name='Courte description')),
                ('category', models.CharField(choices=[('GUIDE', 'Guides & Sensibilisation'), ('REPORT', 'Rapports & Transparence'), ('TOOL', 'Outils Salongo & Technique'), ('LEGAL', 'Documents Officiels')], default='GUIDE', max_length=20)),
                ('file', models.FileField(upload_to='resources/docs/', verbose_name='Fichier (PDF)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resources/covers/', verbose_name='Image de couverture (Optionnel)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
